---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  namespace: iot-app
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8086
    targetPort: 8086
  selector:
    app: influxdb
  type: LoadBalancer
---
