apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
   matchLabels:
    app: locust-exporter
  template:
   metadata:
      labels:
       app: locust-exporter
   spec:
    containers:
    - name: locust-exporter
      image: containersol/locust_exporter
      env:
      - name: LOCUST_EXPORTER_URI
        value: 'http://172.31.23.251:8089'
---
apiVersion: v1
kind: Service
metadata:
  name: locust-exporter
  namespace: monitoring
spec:
  ports:
  - name: http
    protocol: TCP
    port: 9646
    targetPort: 9646
  selector:
    app: locust-exporter

