
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring  # Namespace for monitoring components
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest  # Use the latest Grafana image
        ports:
        - containerPort: 3000  # Grafana web interface port
        env:
        - name: gfpassword  # Set Grafana admin password
          value: gfpassword
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
      volumes:
      - name: grafana-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring  # Namespace for monitoring components
spec:
  selector:
    app: grafana
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer  # Use LoadBalancer type to expose Grafana externally (AWS will provision a load balancer)
